### ISSUE TITLE
Feature: User Authentication 

### ISSUE THREAD

**Issue by Dayanro** [Dayanro/news-feed#4]
## Epic Title
Feature: User Authentication 

### Description
Give users the ability  to sign in to the website.

### List of Tasks

- [x] Task: Create a user model #1

- [x] Task: Create a user model seed #2

- [x] Task: Sign in with username #3
