### ISSUE TITLE
Feature: News feed API

### ISSUE THREAD

**Issue by Dayanro** [Dayanro/news-feed#8]
## Epic Title
Feature: News feed API

### Description
API that provides news about our platform. 

### List of Tasks

- [x] Task: Create a news model. #5

- [x] Task: Post a news item #6

- [x] Task: Get news #7
